### ISSUE TITLE
Commas in the coin notes break collection import functionality

### ISSUE THREAD

**Issue by anwilli5** [anwilli5/coin-collection-android#4]
If a comma is present in the coin notes, imports will fail with the following error:

`Invalid backup file detected (Error 11)`

**Comment by tmcclure1** [comment]
I removed all commas from commentS but still will not import of backups from old phone. Only way it's importing is if collection I  set up as a test is created on new phone!

**Comment by anwilli5** [comment]
@tmcclure1, @sw23's fix should allow you to import your old collection now... Hopefully we can push out the next release of the app that incorporates this fix very soon!
