### ISSUE TITLE
Update the app with the new 2017 coins

### ISSUE THREAD

**Issue by anwilli5** [anwilli5/coin-collection-android#8]
First step - figure out what new coins are needed

**Comment by anwilli5** [comment]
- Pennies
- Nickels
- Dimes
- National Park Quarters
    - Effigy Mounds
    - Frederick Douglass
    - Ozark Riverways
    - Ellis Island
    - George Rogers Clark 
- Half Dollar
- Native American Gold Coin
- Presidential Dollar
    - Ronald Reagan
- First Spouse Gold Coins
    - Patricia Nixon
    - Betty Ford
    - Nancy Reagan

**Comment by anwilli5** [comment]
This should be done with the latest commit (f501ad9)

@sw23 if you could verify that the 2017 coins get added successfully that'd be great!  Thanks!

**Comment by sw23** [comment]
Overall looks good to me.  The image quality of the Pennies looked worse (I think).  It seemed worse than the others.  Other than that everything that I tested looked good.

**Comment by anwilli5** [comment]
I ended up having to fix an issue with the order in which 2017 P and D coins were added to collections that have mint marks (see aafeb9c) but after testing, everything seems to work smoothly. Thanks for your help in reviewing this!
